hash-format = "sha256"

[[files]]
file = "config/ftbquests/quests/chapter_groups.snbt"
hash = "e57d8311aec9f524911ed1313cabf138bb7fa5a2d3ba985a00a2a267ff35ef78"

[[files]]
file = "config/ftbquests/quests/chapters/ad_astra.snbt"
hash = "c10bdee352c9a980e61fdd76833bb27e4b20df5dd4ce19a793937a5d21e74c6b"

[[files]]
file = "config/ftbquests/quests/chapters/ae2.snbt"
hash = "4bdc4e8d6c357083974dc0510686848820ad4be40ec39b82774a3f6658db4c1f"

[[files]]
file = "config/ftbquests/quests/chapters/botania.snbt"
hash = "448daa214779be8e57e09f3f9dee0a4ae75cc0b525db9892c0d045c8a8a4460e"

[[files]]
file = "config/ftbquests/quests/chapters/cc.snbt"
hash = "0caa6f2470f9778c0f1abc00187b092b629b4c3e7d0ddf86948c3658f306e1af"

[[files]]
file = "config/ftbquests/quests/chapters/chemistry.snbt"
hash = "af97b70c39c16c93fd9ece8cbe5a0ff1aacb84403c894d5d215a681d1f4adfcc"

[[files]]
file = "config/ftbquests/quests/chapters/create.snbt"
hash = "f88ff6f0be0045104ad02e396b7889c309175e70fd6bbbfd51f4fb62295fc5a0"

[[files]]
file = "config/ftbquests/quests/chapters/farmers_delight.snbt"
hash = "a88ea81b0ab14b72e37a6a7ed277cd87b9edaf70aac7425ee14b26022bdd7089"

[[files]]
file = "config/ftbquests/quests/chapters/immersive_aircraft.snbt"
hash = "b3d1eb68c93e75725e815a83ef398144d4a49391bff3c0241839c8e0a2ed2015"

[[files]]
file = "config/ftbquests/quests/chapters/mi.snbt"
hash = "72d6da1dfa2fe023f147ee2e2bfbc49e7859c900ee0d0bb502b9189b699b85c9"

[[files]]
file = "config/ftbquests/quests/chapters/tinkers_construct.snbt"
hash = "119518ab6fcae12628e71f02058f8fa1da51d2ce3fdfa1e20c9bb1b4e929fd69"

[[files]]
file = "config/ftbquests/quests/chapters/vanilla.snbt"
hash = "7cfaef924aeb17efc40b7a6ca84e1e9cffe0dfe2ae6403c6985043b767771a1f"

[[files]]
file = "config/ftbquests/quests/data.snbt"
hash = "ed2bcb21b54e4dcb69727ce8b2a64790107fc8cf5f6e56bcd4d1d8fd75e0c80f"

[[files]]
file = "config/semblance.properties"
hash = "ba84add784204ce3f1f73379024d492917771dee981a5d2d47b3f88e3ca4d235"

[[files]]
file = "config/styled-chat.json"
hash = "be191f74ff9f87c6ad82960ddb3ce6c72a02905c7f1b9681fa8c6cbb31d6a58c"

[[files]]
file = "config/styledplayerlist/config.json"
hash = "c8db949a3f89485da95b201f596732a1ba8f56a00452e68932c89e50db278688"

[[files]]
file = "config/styledplayerlist/styles/default.json"
hash = "96611cf3bb56261c7ebd1b1293234a567348d62eb35cf19d97d8c39405562a75"

[[files]]
file = "mods/EasyAuth/config.json"
hash = "16212222927ec9f7338489632005fd16092dbea27c3231b61ec283f740582022"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "034718706cd7bc9baca522753dc62e779d5025ecf7a6a9b9c1d0a2b18b73d967"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "3475ed31cc03e95979ed05849015a59a38e286c86093c58d41013f3d945f72fe"
metafile = true

[[files]]
file = "mods/ae2-emi-crafting.pw.toml"
hash = "b754342449d8c7d9bcc7cd7f425dd0bd29fb22431529b8238e62e94de412ba04"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "0c9015aa5398140bff02d2c2f8f837e5b903ac53ca7c2496afb98e30cf08285b"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e3dfb2478e6bb096667d4ec89b0ddfef627747939373bdefee02f358d6e3dee1"
metafile = true

[[files]]
file = "mods/applied-botanics.pw.toml"
hash = "eb4377f8e33d5040f2aaf9fde5c5799159db864b91fab6908ef12bb1836483e3"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "67d1dac247ae7af173e15fa747cdb301c5fd9fdaa395840d683cd03b5913956b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "13cb21e09b9d0d6622359f24f0bfed0e4123fcbaf7e65a1eb7e5396c47a56349"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "e5a68e0e0d90aac1d965ab7cab5858c474e875be9012a7c8a3adf96420faa726"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "e0939ffb6b7b49dde8f936cd83f6f4881238f71bbdf14afe3b22b364b7e8cfbe"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "89d7f1597acb08c364ac7d36a528cd7317f98e2bad5ccedfa54192a57246b8bb"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "d4b79652245914a4f376f13a0a11c12b624613be9df788e227572ee7f5281f6c"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "8c47daba91f742d52311a9df66bae3296246ecba7ca6f1650579e5739d152d0f"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "b79cc58d8f59edf82a64eac716b84f11911b2bc63c40529575dbaf67f4896efb"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "d94da74c5f4dce9b7b6586f04b3bfe99ff2b2b5298258b8ab9b111c1c126bb67"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a89dfcc985612a275975d4823a24fc3dceb244bacb2e8f81bd459283bf1b9fe9"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "4446114023212017387263c94e75b9e3ff626289a8802c34bfc3813de2ebbd1e"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "4509d50ad87085fdcb9c950ce9ba12a0a95686fefa649d426ca8bd552d0203ee"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "35faa81d6d6ece695162f22604b1a987669e5fce7742dbd27c9cdd43b512b9d2"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "0372b9ea1233cf516f205bed50c4014bfb4e806406657b8f803409a71d81d88a"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
hash = "8eb262e41270d2dc38033a31e68ce9e80d664c5912afd95193c4158d7641c062"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric.pw.toml"
hash = "c444817bb4da81488458646b19c2c4ad49284d9a99961a61958628c71c0dfced"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
hash = "da0b1e65c3bb9f9eabfbaf4242b3adf22267752adb3824fe62b24077cf458340"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "26394151533372bce2229f31c8df7f65e2deb751cc823f317cd30682381acc8f"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "93f8459ef551d239aba91b04529a2fa9bc8fe3630000e1478928e7900b4ae22c"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "246738f5a6bb9726299202fbe7a639ca214cf704e3ea6ca20414b9600c0a7412"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
hash = "e25a9439cd57c1af53a62c6f8703934911a561f38330e5acfb482a82ab09a404"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "4fac0263f4d5e5b8810969b6a04b64ee2396cd42232fd16bcadf7e8e7ae96d90"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "d7efd7d686ed6465c3eb2a71a5be177876a774388fbb31804c29f3c55141b8df"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "a4a87e7580a1651f429af181e1be40a5b3c4b1969f80288c5199dcde91592ee7"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "6ed9dba064110665c3dcf26be139c68b290ef0079e8aece1d2aced9484ebf85b"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "b00063ae4ce84453b6cb813c7aa3fee8083a1dd8d5110325409ea10e75e6c89f"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
hash = "2ad35d1b513308d702e9fe45f3c711d63dd1abb8fcbbb40d9a1d7c37d4d5d367"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
hash = "a55d562fcd6be9796e8cc162b83b5745efd83254fae44bf5a4d85d0fe6c97fcb"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9f499eff7ddb9eeab719f19808cbcf41f2b77d06ebf946f157cf7b5f52f64e70"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "b596d10a9b700d570d729f2f04b892d1a7715c5af434a998dc0c15a7596b05d7"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
hash = "3ae3bffdac2e274dd7ba6feaf76f89572dbf97c025cfa8c798978c089e309620"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "86698b1faa9bf449eab492509239372302311092104be467108d7e05127e91f1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "14e87ff6253d2bd02697e46b4a9b5060465d72b71663def5236f829e30bac6d6"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "ee9bd23aea09a314966d57a211d84aa288e7803c4277c6996edac334eee77c58"
metafile = true

[[files]]
file = "mods/faux-custom-entity-data.pw.toml"
hash = "a4da8bc46ad51d30597bd2235add659f0ee49123a7140487de7d127659a87e4b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "8a7f673c71c9523fded9f5bfd607424f8d6109d7d3b387ce703e86f28d4d9cf5"
metafile = true

[[files]]
file = "mods/ftb-quests-fabric.pw.toml"
hash = "65230127d2f844c7feabe3883f93125b2eb0d354c14a9cbbd81bdc6b668cb490"
metafile = true

[[files]]
file = "mods/ftb-teams-fabric.pw.toml"
hash = "4b6e750998339114bf081528a710bf1f0090b52b9c83b971a727dd55157b67f7"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "7a0ddae74ef4a6015f9919459f49624bbddd7f3891dbaae71ea042456b6f44b8"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "2dded9237b5fbf729ca1947780e8de50bfaaad8b95371370e5263620122bad20"
metafile = true

[[files]]
file = "mods/hephaestus.pw.toml"
hash = "a956c6e7dea778d088b0059ba7019c139b9477d80bab38a22fa00e4b984a94af"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "1aadf91846b80dcbedfae8433ff58b5614b3470062887fe9b3d1e22d05ed0e86"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "31278d67704a56eb32d93c240e4bfd9822e1ab6047ee14d752953dd0c24dca95"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "957fccf5d7bb580339b0ac2b8de2986415ef83fe297963e888e97d2063afefc3"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "aac37788ac1acd537a8b5b32fc2489cddf8034f196f7f38c0755837764b4f01d"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
hash = "58567b23252ec837faa0d3ab12c85b0315b6e3101da0337631d7f49893b962f4"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "84defc8f8116d5c0e4210934ed1f555641a1db71b767fa4beddee21c47118868"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "7826b93c7f36611fbd9190481774daa349fa403875f8522d0ca4302e1345bd40"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
hash = "ed2ff97cf59a6c5b9f4e509edbc8c48944bb3c98795f6738c8dfec353cbe350d"
metafile = true

[[files]]
file = "mods/mc-249136-fix.pw.toml"
hash = "4caef00d584b5a6394b9b09a373f755bf62e3b3e7fc44da94883c51fc087d77d"
metafile = true

[[files]]
file = "mods/megane.pw.toml"
hash = "b0bc82b0c52bcdef851e0e0e055f6a65f3c2fe6b8a3e255f0dc32a3ed6b6ac08"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "3c0945a312aca06a2185b00cb03ae482949b008d72614497148aa2df301af019"
metafile = true

[[files]]
file = "mods/modern-industrialization-sound-addon.pw.toml"
hash = "a474795be2ba5daae8a0cce33867f6dbddccbbb943ae169c40cea4c22b09f265"
metafile = true

[[files]]
file = "mods/modern-industrialization.pw.toml"
hash = "80f08f5c54fd3c97cee597002942ae37617ceadf7b00dd6a239a8c17b655745c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "37976a6d30855b8e6670193cb07f969df75ed89616223daf3b72a20f75dee4d8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "f4571bec7e1ffd860712cc69b077c9876eca35ed8c64424a9f4b6e11314ae831"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9ecf3bd4cd96af63bb04063f74b8a13cea46a77bfce670b4408417f8d0d293e0"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "a53ec69b860f0d71746a657200adb02c75e5f0e9b95277058fc556853634ca40"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "e7712ecf20e3c2e52da19f968762b671726222cbc4c48206231b56b6c6cd79a7"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
hash = "41f18dab192c79a4f4ec38422b38c3d6198ebae71abab86cfbf305a1d008c051"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "a8e48a0dadfaa8492f5e46ed3555dcaa2f6cb15bf7b7819fef018ec3e60d3706"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "0f9916dcded3aac68d56113e9617bbe3db5ec9036bd9bba784bc40a961b0c9f0"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "4d4bcf62b73bcc53dbb6d9edfe0ed84b4ad9c267a37807c0c653486add6f89a8"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "cd7b16dc449e4795d9bda1a38a20e2a2a835064e92cf47b28a29d03388a43ed5"
metafile = true

[[files]]
file = "mods/semblance.pw.toml"
hash = "53a51bd94cb0b6a59567a22854f110e7d454aaaf158612c87737b39498a7930c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5379b1da9fa50def37ede26e66dd963de3ce6f8576cd60a6b117998e09a5597c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "245530bdbb5c4127a1286f3722778d71e478194a8dcee89388c8fd247b4a57da"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "96e3771cd09bb4a808d1c1fcb5a050efdc2ffb4efe7b584407ed54c46c0388d9"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "621e56ad677649509141a20b4a4a6042ea30af69c1527153681f8f2c4cf0104b"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "18cb5a5474406d7af310b53c93a983ffa608b03213f9d325e81dff3239566eb1"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "27c9ee50e624c436e1bb6fe4bbeff166f5c6564e9f9a846ffef22e54a200c603"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "075b0a946ee6bc32d2eadde90257bdf53d09493978b3b7add5af49716691799e"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "515c7bc565f95c472aa347085937d4f96e02498ac68b15158a723fe876a3d3fb"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "07619668821f2aad9dbd40084ad80f25595d8715a9ef204a4a9629225729a7d9"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "e39b6be6d8465829fe40a2e42d3a86dbde2266a7c7cf48ba2d5741baa1749cae"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "b08fbe1bb98f55707b93046332d999ad5bd2a3c55fd62b6269fb203c8312457d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "74a5d6dc2fa3494650bf951f2212c70eeb6b8d1af209b5dab4b7a8582302865c"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "a66f114b66d41c0de64f6d7cb00d253b858ecb8dfef497aed5feac1a690111a2"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "5fa3a100f874ad3d03b674e867105fc7cc7dcf98b5c1c50d7841a25a0dda4607"
metafile = true

[[files]]
file = "resourcepacks/ccc.pw.toml"
hash = "a864f90ec46c0f6dcd94b19d214d02b8605b00dfa568f36d2d5a08d819d6c9ff"
metafile = true

[[files]]
file = "resourcepacks/create-computercraft.pw.toml"
hash = "92330acf54623b70104adb84139372a43045cff7066e7068da757a4de212b07d"
metafile = true

[[files]]
file = "scripts/custom_create_recipes.zs"
hash = "a0d2ff25c8a8bfe373cb7508e1bd4196f2bb9fc38f23fba1a73a2e56989da300"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "41fbddad14b67a342e35eb7d2c96cfb555014c0f9c0e1e2866a3d2516a33c971"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "88e40e1591ad381291207cce0d547507ae6ca44893185a1e7ef37b7b86f29e57"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "8a98b97853c1acd591c51aecdd3010481f894b651a29af8262b07b30be60d4d7"
metafile = true
